### ISSUE TITLE
Stations

### ISSUE THREAD

**Issue by pietercolpaert** [linkedconnections/server.js#4]
We need to be able to have a search interface for stops. Functionality we need: 
 * Return the full list of stops (paged if necessary), with their name, parentStop, lon, lat and additional info
 * Full text search to get from a station name to a URI for a stop
 * Geo-features: select the stops by filtering on their long/lat in a bounding box, radius, etc.

All this needs to be done while keeping the server load as low as possible

**Comment by brechtvdv** [comment]
For the paginator of the stops: do you want this to be implemented inside the existing paginator with own methods, or do you prefer a connectionsPaginator and stopsPaginator?

**Comment by pietercolpaert** [comment]
I don't want to focus on this right now, but I was thinking about just using ldf-server for this and requiring it using LDF.

For a first version, we should indeed go for a ConnectionsPaginator and StopsPaginator

**Comment by pietercolpaert** [comment]
Closing for now, station information should be fetched using other Linked Data querying systems
